export const FETCH_DATA = '@SETTINGS/FETCH_DATA';
export const DATA_FETCHED = '@SETTINGS/DATA_FETCHED';
export const ERROR_IN_FETCHING_DATA = '@SETTINGS/ERROR_IN_FETCHING_DATA';

export const SAVE_DATA_IN_STATE = '@SETTINGS/SAVE_DATA_IN_STATE';
export const SAVE_DATA_IN_DB = '@SETTINGS/SAVE_DATA_IN_DB';
export const DATA_SAVED_IN_DB = '@SETTINGS/DATA_SAVED_IN_DB';
export const ERROR_SAVING_DATA_IN_DB = '@SETTINGS/ERROR_SAVING_DATA_IN_DB';

export const ENABLE_CSRF = '@SETTINGS/ENABLE_CSRF';
export const DISABLE_CSRF = '@SETTINGS/DISABLE_CSRF';
