export const LOAD_DATA = '@SETTINGS/LOAD_DATA';
export const DATA_LOADED = '@SETTINGS/DATA_LOADED';
export const ERROR_IN_LOADING_DATA = '@SETTINGS/ERROR_IN_LOADING_DATA';

export const SAVE_DATA = '@SETTINGS/SAVE_DATA';
export const SAVE_IN_DB = '@SETTINGS/SAVE_IN_DB';
export const SAVED_IN_DB = '@SETTINGS/SAVED_IN_DB';
export const ERROR_IN_SAVING_DATA = '@SETTINGS/ERROR_IN_SAVING_DATA';

export const ENABLE_CSRF = '@SETTINGS/ENABLE_CSRF';
export const DISABLE_CSRF = '@SETTINGS/DISABLE_CSRF';
