export const FETCH_DATA = '@SETTINGS/FETCH_DATA';
export const DATA_FETCHED = '@SETTINGS/DATA_FETCHED';
export const ERROR_IN_FETCHING_DATA = '@SETTINGS/ERROR_IN_FETCHING_DATA';

export const SAVE_DATA_IN_STATE = '@SETTINGS/SAVE_DATA_IN_STATE';
export const SAVE_DATA_IN_DB = '@SETTINGS/SAVE_DATA_IN_DB';
export const DATA_SAVED_IN_DB = '@SETTINGS/DATA_SAVED_IN_DB';
export const ERROR_SAVING_DATA_IN_DB = '@SETTINGS/ERROR_SAVING_DATA_IN_DB';

export const UPDATE_DATA_IN_DB = '@SETTINGS/UPDATE_DATA_IN_DB';
export const DATA_UPDATED_IN_DB = '@SETTINGS/DATA_UPDATED_IN_DB';
export const ERROR_UPDATING_DATA_IN_DB = '@SETTINGS/ERROR_UPDATING_DATA_IN_DB';

export const FETCH_CSRF_DATA = '@SETTINGS/FETCH_CSRF_DATA';
export const CSRF_DATA_FETCHED = '@SETTINGS/CSRF_DATA_FETCHED';
export const ERROR_IN_FETCHING_CSRF_DATA =
  '@SETTINGS/ERROR_IN_FETCHING_CSRF_DATA';

export const ENABLE_CSRF = '@SETTINGS/ENABLE_CSRF';
export const CSRF_ENABLED = '@SETTINGS/CSRF_ENABLED';
export const ERROR_IN_ENABLING_CSRF = '@SETTINGS/ERROR_IN_ENABLING_CSRF';

export const DISABLE_CSRF = '@SETTINGS/DISABLE_CSRF';
export const CSRF_DISABLED = '@SETTINGS/CSRF_DISABLED';
export const ERROR_IN_DISABLING_CSRF = '@SETTINGS/ERROR_IN_DISABLING_CSRF';
