export const LOADING = '@MAIN/LOADING';
export const LOADING_COMPLETE = '@MAIN/LOADING_COMPLETE';

export const FETCH_DATA = '@MAIN/FETCH_DATA';
export const DATA_FETCHED = '@MAIN/DATA_FETCHED';
export const ERROR_IN_DATA_FETCH = '@MAIN/ERROR_IN_DATA_FETCH';

export const TOGGLE_SIDEBAR = '@MAIN/TOGGLE_SIDEBAR';
